Objective:

Store the cleaned retail sales dataset inside PostgreSQL and perform SQL analysis.

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv("data/processed/superstore_cleaned.csv")

In [6]:
DATABASE_URL = "postgresql://postgres:22332233@localhost:5432/retail_sales_db"

engine = create_engine(DATABASE_URL)

print("Connected Successfully")

Connected Successfully

In [10]:
df.to_sql(
    "superstore",
    engine,
    if_exists="replace",
    index=False
)

print("Dataset Uploaded Successfully")

Dataset Uploaded Successfully

In [11]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

pd.read_sql(query, engine)

   table_name
0  Superstore
1  superstore

In [12]:
query = """
SELECT *
FROM superstore
LIMIT 5;
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Year,Month,Month Name,Quarter,Day,Shipping Days
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,11,November,4,8,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,11,November,4,8,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,6,June,2,12,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,10,October,4,11,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,10,October,4,11,7


# Total Sales

In [13]:
query = """
SELECT
SUM("Sales") AS Total_Sales
FROM superstore;
"""

pd.read_sql(query, engine)

    total_sales
0  2.297201e+06

# total Profit

In [14]:
query = """
SELECT
SUM("Profit") AS Total_Profit
FROM superstore;
"""

pd.read_sql(query, engine)

   total_profit
0   286397.0217

# Sales by Category

In [15]:
query = """
SELECT
"Category",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Category"

ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

          Category  total_sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

# Profit by Category

In [16]:
query = """
SELECT
"Category",
SUM("Profit") AS Total_Profit

FROM superstore

GROUP BY "Category"

ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, engine)

          Category  total_profit
0       Technology   145454.9481
1  Office Supplies   122490.8008
2        Furniture    18451.2728

# Sales by Region

In [17]:
query = """
SELECT
"Region",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Region"

ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

    Region  total_sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

# Top 10 Customers

In [18]:
query = """
SELECT
"Customer Name",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Customer Name"

ORDER BY Total_Sales DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

        Customer Name  total_sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

# Top 10 Products

In [19]:
query = """
SELECT
"Product Name",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Product Name"

ORDER BY Total_Sales DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

                                        Product Name  total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

# Monthly Sale

In [20]:
query = """
SELECT
"Year",
"Month",
SUM("Sales") AS Monthly_Sales

FROM superstore

GROUP BY "Year","Month"

ORDER BY "Year","Month";
"""

pd.read_sql(query, engine)

    Year  Month  monthly_sales
0   2014      1     14236.8950
1   2014      2      4519.8920
2   2014      3     55691.0090
3   2014      4     28295.3450
4   2014      5     23648.2870
5   2014      6     34595.1276
6   2014      7     33946.3930
7   2014      8     27909.4685
8   2014      9     81777.3508
9   2014     10     31453.3930
10  2014     11     78628.7167
11  2014     12     69545.6205
12  2015      1     18174.0756
13  2015      2     11951.4110
14  2015      3     38726.2520
15  2015      4     34195.2085
16  2015      5     30131.6865
17  2015      6     24797.2920
18  2015      7     28765.3250
19  2015      8     36898.3322
20  2015      9     64595.9180
21  2015     10     31404.9235
22  2015     11     75972.5635
23  2015     12     74919.5212
24  2016      1     18542.4910
25  2016      2     22978.8150
26  2016      3     51715.8750
27  2016      4     38750.0390
28  2016      5     56987.7280
29  2016      6     40344.5340
30  2016      7     39261.9630
31  2016      8     31115.3743
32  2016      9     73410.0249
33  2016     10     59687.7450
34  2016     11     79411.9658
35  2016     12     96999.0430
36  2017      1     43971.3740
37  2017      2     20301.1334
38  2017      3     58872.3528
39  2017      4     36521.5361
40  2017      5     44261.1102
41  2017      6     52981.7257
42  2017      7     45264.4160
43  2017      8     63120.8880
44  2017      9     87866.6520
45  2017     10     77776.9232
46  2017     11    118447.8250
47  2017     12     83829.3188

# Average Shipping Days

In [21]:
query = """
SELECT
AVG("Shipping Days") AS Average_Shipping_Days

FROM superstore;
"""

pd.read_sql(query, engine)

   average_shipping_days
0               3.958175

# Highest Profit State

In [22]:
query = """
SELECT
"State",
SUM("Profit") AS Profit

FROM superstore

GROUP BY "State"

ORDER BY Profit DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

        State      profit
0  California  76381.3871
1    New York  74038.5486
2  Washington  33402.6517
3    Michigan  24463.1876
4    Virginia  18597.9504
5     Indiana  18382.9363
6     Georgia  16250.0433
7    Kentucky  11199.6966
8   Minnesota  10823.1874
9    Delaware   9977.3748

# Highest Discount Products

In [23]:
query = """
SELECT
"Product Name",
AVG("Discount") AS Average_Discount

FROM superstore

GROUP BY "Product Name"

ORDER BY Average_Discount DESC

LIMIT 10;
"""

pd.read_sql(query, engine)

                                        Product Name  average_discount
0  Eureka Disposable Bags for Sanitaire Vibra Gro...          0.800000
1                     GBC Plasticlear Binding Covers          0.728571
2            GBC VeloBinder Electric Binding Machine          0.725000
3                Epson Perfection V600 Photo Scanner          0.700000
4        Lexmark MarkNet N8150 Wireless Print Server          0.700000
5                               Okidata B401 Printer          0.700000
6                     Plantronics Single Ear Headset          0.700000
7  Bush Westfield Collection Bookcases, Dark Cher...          0.700000
8  Hewlett-Packard Deskjet F4180 All-in-One Color...          0.700000
9  Brother MFC-9340CDW LED All-In-One Printer, Co...          0.700000

# SQL Business Insights

1. Technology generated the highest sales.

2. Technology generated the highest profit.

3. West region generated the highest revenue.

4. Consumer customers generated the largest sales.

5. California generated the highest sales.

6. Average shipping time is approximately 4 days.